spring:
  application:
    name: douid-brand-api

  jackson:
    time-zone: UTC

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

media:
  upload:
    dir: ./uploads/media
    max-size: 10485760
