-- Flyway 도입 이전 ddl-auto(create/update)로 관리되던 스키마를 baseline으로 고정한다.
-- 각 테이블/컬럼 구성은 Hibernate가 현재 엔티티 매핑으로 생성한 DDL을 그대로 옮긴 것이다.

CREATE TABLE admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role = 'ADMIN'),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT admins_email_key UNIQUE (email)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL,
    visible BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT categories_slug_key UNIQUE (slug)
);

CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT media_stored_filename_key UNIQUE (stored_filename)
);

CREATE TABLE works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    summary VARCHAR(255),
    description TEXT,
    category_id BIGINT,
    visibility VARCHAR(20) NOT NULL CHECK (visibility IN ('VISIBLE', 'HIDDEN')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT works_slug_key UNIQUE (slug),
    CONSTRAINT fk_works_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE work_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('THUMBNAIL', 'DETAIL_IMAGE', 'ATTACHMENT')),
    sort_order INTEGER NOT NULL,
    alt_text VARCHAR(255),
    CONSTRAINT fk_work_media_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_work_media_media FOREIGN KEY (media_id) REFERENCES media (id)
);

CREATE TABLE client_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE client_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_identity_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked BOOLEAN NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT client_credential_token_hash_key UNIQUE (token_hash),
    CONSTRAINT fk_client_credential_client_identity FOREIGN KEY (client_identity_id) REFERENCES client_identity (id)
);

CREATE TABLE client_email (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_identity_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    normalized_email VARCHAR(255) NOT NULL,
    verified_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_client_email_client_identity FOREIGN KEY (client_identity_id) REFERENCES client_identity (id)
);

-- 검증 완료된(verified_at IS NOT NULL) 이메일만 normalized_email 유일성을 보장한다.
-- 검증 전 challenge 단계에서는 동일 이메일로 여러 시도가 있을 수 있어 조건부(partial) index로 제한한다.
CREATE UNIQUE INDEX client_email_normalized_email_verified_key
    ON client_email (normalized_email)
    WHERE verified_at IS NOT NULL;

CREATE TABLE email_verification_challenge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_identity_id BIGINT NOT NULL,
    normalized_email VARCHAR(255) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    consumed_at TIMESTAMP(6),
    attempt_count INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_email_verification_challenge_client_identity FOREIGN KEY (client_identity_id) REFERENCES client_identity (id)
);

CREATE TABLE client_recovery_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_identity_id BIGINT NOT NULL,
    client_email_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    consumed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT client_recovery_token_token_hash_key UNIQUE (token_hash),
    CONSTRAINT fk_client_recovery_token_client_identity FOREIGN KEY (client_identity_id) REFERENCES client_identity (id),
    CONSTRAINT fk_client_recovery_token_client_email FOREIGN KEY (client_email_id) REFERENCES client_email (id)
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL,
    client_identity_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'CLOSED')),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT conversation_public_id_key UNIQUE (public_id),
    CONSTRAINT fk_conversation_client_identity FOREIGN KEY (client_identity_id) REFERENCES client_identity (id)
);

CREATE TABLE message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id)
);
